/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client"
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from "three";
useGLTF.preload("/AlogzaTab/AlogzaTab.gltf");

const screenTextures = {
    codeScreen: "/labels/CodeAlogza.png",
    Whyus: "/labels/whyusfull.jpg",
    Whyus1: "/labels/Whyus1Tx.jpg",
    Whyus2: "/labels/Whyus2Tx.jpg",
    logo:"/labels/Logo.png"
}

export type TabProps={
    screen?: keyof typeof screenTextures;
    scale?: number;
    screenOffset: number;
};

export function AlogzaTab({
    screen = "codeScreen",
    scale = 0.1,
    screenOffset = 0.095,
    ...props
}: TabProps)
{
    const { nodes, materials } = useGLTF('/AlogzaTab/AlogzaTab.gltf');
    const labels = useTexture(screenTextures);

    labels.codeScreen.flipY = false;
    labels.Whyus.flipY = false;
    labels.Whyus.offset.set(screenOffset, 0); // Adjust the offset to center the texture
    labels.Whyus.repeat.set(0.3,1);
    labels.Whyus2.flipY = false;
    labels.Whyus2.offset.set(.13, 0); // Adjust the offset to center the texture
    labels.Whyus2.repeat.set(.7,1);
    labels.logo.flipY = false;

    const logo = labels.logo;

    const metalMaterial = new THREE.MeshStandardMaterial({
        map: labels[screen],       // Apply screen texture
        roughness: 0.3,
        metalness: 1,
        emissive: new THREE.Color(0xffffff), // Emissive color (white light)
        emissiveMap: labels[screen], // Use texture as emissive map
        emissiveIntensity: 2,  // Adjust brightness        
    })

    return (
    <group {...props} dispose={null} scale={scale} rotation={[Math.PI, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes['Asset_2@4x-8001'] as THREE.Mesh).geometry}
              material={materials['Asset 2@4x-8.001']}
              position={[0.089, 0.027, 0.226]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={1.023}
            >
            <meshStandardMaterial roughness={0.15} metalness={0.7} map={logo}/>

            </mesh>
            <group position={[0.084, -2.39, 0.078]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={6.064}>
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.iPad_Pro_2020_Body_0_1 as THREE.Mesh).geometry}
            material={materials.Body}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.iPad_Pro_2020_Body_0_2 as THREE.Mesh).geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.iPad_Pro_2020_Body_0_3 as THREE.Mesh).geometry}
            material={materials.Line}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.iPad_Pro_2020_Body_0_4 as THREE.Mesh).geometry}
            material={materials.LiDar}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.iPad_Pro_2020_Body_0_5 as THREE.Mesh).geometry}
            material={materials.bezel}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.iPad_Pro_2020_Body_0_6 as THREE.Mesh).geometry}
            material={materials.glass}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.iPad_Pro_2020_Body_0_7 as THREE.Mesh).geometry}
            material={materials.front_camera}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.iPad_Pro_2020_Body_0_8 as THREE.Mesh).geometry}
            material={materials.camera12}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.iPad_Pro_2020_Body_0_9 as THREE.Mesh).geometry}
            material={materials['zCLdUynNQOzVMqx.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.iPad_Pro_2020_Body_0_10 as THREE.Mesh).geometry}
            material={materials.material_12}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.iPad_Pro_2020_Body_0_11 as THREE.Mesh).geometry}
            material={materials.cameraframe_and_logo}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.iPad_Pro_2020_Body_0_12 as THREE.Mesh).geometry}
            material={materials.camera2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.iPad_Pro_2020_Body_0_13 as THREE.Mesh).geometry}
            material={materials.camera1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.iPad_Pro_2020_Body_0_14 as THREE.Mesh).geometry}
            material={materials['camera2.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.iPad_Pro_2020_Body_0_15 as THREE.Mesh).geometry}
            material={materials.Camera_Flash}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.iPad_Pro_2020_screen_0 as THREE.Mesh).geometry}
          material={metalMaterial}
          position={[0.084, -2.39, 0.078]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={6.064}
        >
        <meshStandardMaterial  roughness={0.15} metalness={0.7} map={labels[screen]}/>
        </mesh>
      </group>
      )
    }