/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client"
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from "three";
import { useTranslation } from "react-i18next";

useGLTF.preload("/AlogzaLaptop/AlogzaLaptop.gltf");

const screenTextures = {
    codeScreen: "/labels/CodeAlogza.png",
    logo:"/labels/Logo.png"
}

export type LaptopProps={
    screen?: keyof typeof screenTextures;
    scale?: number;
};

export function AlogzaLaptop({
    screen = "codeScreen",
    scale = 0.1,
    ...props
}: LaptopProps)
{
    const { nodes, materials } = useGLTF('/AlogzaLaptop/AlogzaLaptop.gltf');
    const labels = useTexture(screenTextures);
    const { i18n } = useTranslation();

    labels.codeScreen.flipY = false;
    labels.logo.flipY = false;

    const codeScreen = labels[screen];
    const logo = labels.logo;

    const metalMaterial = new THREE.MeshStandardMaterial({
        map: codeScreen,       // Apply screen texture
        roughness: 0.3,
        metalness: 1,
        emissive: new THREE.Color(0xffffff), // Emissive color (white light)
        emissiveMap: codeScreen, // Use texture as emissive map
        emissiveIntensity: 2,  // Adjust brightness        
    })

    let ritateX = -0.44;
    if (i18n.language === "ar") {
      ritateX = 0.44;
    } else if (i18n.language === "en") {
      ritateX = -0.44;
    }

    return (
    <group {...props} dispose={null} scale={scale} rotation={[.4, ritateX, .04]}>
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes['Asset_2@4x-8'] as THREE.Mesh).geometry}
              material={materials['Asset 2@4x-8']}
              position={[-0.362, 2.087, -3.197]}
              rotation={[1.225, 0, 0]}
              scale={1.203}
            >
            <meshStandardMaterial roughness={0.15} metalness={0.7} map={logo}/>

            </mesh>
            <group position={[-0.346, -0.053, -0.085]} rotation={[Math.PI / 2, 0, 0]} scale={0.181}>
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_1 as THREE.Mesh).geometry}
                material={materials.bsEIHfblEXNcUMs}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_2 as THREE.Mesh).geometry}
                material={materials.wjAYtisbflXilXi}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_3 as THREE.Mesh).geometry}
                material={materials.zobIbiekuagXEVU}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_4 as THREE.Mesh).geometry}
                material={materials.AibnXCKcAbewWhH}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_5 as THREE.Mesh).geometry}
                material={materials.WeLyzRwUVIhQGgM}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_6 as THREE.Mesh).geometry}
                material={materials.UhoCLqHkvkDmxOA}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_7 as THREE.Mesh).geometry}
                material={materials.zhGRTuGrQoJflBD}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_8 as THREE.Mesh).geometry}
                material={materials.zCLdUynNQOzVMqx}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_9 as THREE.Mesh).geometry}
                material={materials.jwuTsnFxKtBUxpK}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_10 as THREE.Mesh).geometry}
                material={materials.lmWQsEjxpsebDlK}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_11 as THREE.Mesh).geometry}
                material={materials.MycfwscjQZRVSoj}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_12 as THREE.Mesh).geometry}
                material={materials.bsmYIMHYRqMuLqz}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_13 as THREE.Mesh).geometry}
                material={materials.LtEafgAVRolQqRw}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_14 as THREE.Mesh).geometry}
                material={materials.iyDJFXmHelnMTbD}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_15 as THREE.Mesh).geometry}
                material={materials.JvMFZolVCdpPqjj}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_16 as THREE.Mesh).geometry}
                material={materials.eJObPwhgFzvfaoZ}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_17 as THREE.Mesh).geometry}
                material={materials.UBYmHfGRfHbOXyc}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_18 as THREE.Mesh).geometry}
                material={materials.nDsMUuDKliqGFdU}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_19 as THREE.Mesh).geometry}
                material={materials.CRQixVLpahJzhJc}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_20 as THREE.Mesh).geometry}
                material={materials.IcpudUyxprDYhfw}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_21 as THREE.Mesh).geometry}
                material={materials.uInNDOueKeBTGQB}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_22 as THREE.Mesh).geometry}
                material={materials.YYwBgwvcyZVOOAA}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_23 as THREE.Mesh).geometry}
                material={materials.SLGkCohDDelqXBu}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_24 as THREE.Mesh).geometry}
                material={materials.WDumMKBWVQxmraD}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_25 as THREE.Mesh).geometry}
                material={materials.WnHKXHhScfUbJQi}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_26 as THREE.Mesh).geometry}
                material={materials.gOXiFODBFKnUyyU}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_27 as THREE.Mesh).geometry}
                material={materials.ZNhRrZtaKWQYAab}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_28 as THREE.Mesh).geometry}
                material={materials.eBwkWuOBScacrgP}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_29 as THREE.Mesh).geometry}
                material={materials.fNHiBfcxHUJCahl}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_30 as THREE.Mesh).geometry}
                material={materials.SABLxXNNESCdgUy}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_31 as THREE.Mesh).geometry}
                material={materials.LpqXZqhaGCeSzdu}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_32 as THREE.Mesh).geometry}
                material={materials.sIfSZcqgDlKMJPf}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_33 as THREE.Mesh).geometry}
                material={materials.ZCDwChwkbBfITSW}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_34 as THREE.Mesh).geometry}
                material={materials.gMtYExgrEUqPfln}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_35 as THREE.Mesh).geometry}
                material={materials.XCYkeTCxqFmKTKe}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_36 as THREE.Mesh).geometry}
                material={materials.hmEmmncwVomyUTC}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_37 as THREE.Mesh).geometry}
                material={materials.KclpPzxoRwZAoer}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.SDuwtEsnNduSSwf_38 as THREE.Mesh).geometry}
                material={materials.RyKTMHTpkkwQkvB}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.VQmfhbMzfNAuKAD as THREE.Mesh).geometry}
              material={metalMaterial}
              position={[-0.346, 0.019, -2.395]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.181}
            >
            <meshStandardMaterial roughness={0.15} metalness={0.7} map={codeScreen}/>

            </mesh>
        </group>
      )
    }